{"name":"Wingtip Sales Dataflow","description":"","version":"1.0","culture":"en-US","modifiedTime":"2019-10-21T17:54:50.1618626+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Customers":{"queryId":"58d2a7e0-0298-4d94-8285-7af1f3d54b15","queryName":"Customers","loadEnabled":true},"Products":{"queryId":"10577951-df4b-407c-b6fb-c923880ba1ed","queryName":"Products","loadEnabled":true},"Orders":{"queryId":"ad08816d-be0d-4f6f-b19e-755f23c8fb0f","queryName":"Orders","loadEnabled":true},"Sales":{"queryId":"4613190e-da33-4a3a-af5d-a567cbde4dd2","queryName":"Sales","loadEnabled":true}},"document":"section Section1;\r\nshared Customers = let\r\n  Source = Sql.Database(\"cpt.database.windows.net\", \"WingtipSalesDB\"),\r\n  dbo_Customers = Source{[Schema = \"dbo\", Item = \"Customers\"]}[Data],\r\n  #\"Removed Other Columns\" = Table.SelectColumns(dbo_Customers, {\"CustomerId\", \"FirstName\", \"LastName\", \"City\", \"State\", \"Zipcode\", \"Gender\", \"BirthDate\", \"FirstPurchaseDate\", \"LastPurchaseDate\"}),\r\n  #\"Merged Columns\" = Table.CombineColumns(#\"Removed Other Columns\", {\"FirstName\", \"LastName\"}, Combiner.CombineTextByDelimiter(\" \", QuoteStyle.None), \"Customer\"),\r\n  #\"Replaced Female Values\" = Table.ReplaceValue(#\"Merged Columns\", \"F\", \"Female\", Replacer.ReplaceText, {\"Gender\"}),\r\n  #\"Replaced Male Values\" = Table.ReplaceValue(#\"Replaced Female Values\", \"M\", \"Male\", Replacer.ReplaceText, {\"Gender\"}),\r\n  #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Male Values\", {{\"FirstPurchaseDate\", type date}, {\"LastPurchaseDate\", type date}, {\"BirthDate\", type date}}),\r\n  #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Customer Type\", each if [FirstPurchaseDate] = [LastPurchaseDate] then \"One-time Customer\" else \"Repeat Customer\"),\r\n  #\"Removed Columns\" = Table.RemoveColumns(#\"Added Conditional Column\", {\"FirstPurchaseDate\", \"LastPurchaseDate\"}),\r\n  #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Columns\", {{\"Customer Type\", type text}}),\r\n  #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\", {{\"City\", \"City Name\"}})\r\nin\r\n  #\"Renamed Columns\";\r\nshared Products = let\r\n  Source = Sql.Database(\"cpt.database.windows.net\", \"WingtipSalesDB\"),\r\n  dbo_Products = Source{[Schema = \"dbo\", Item = \"Products\"]}[Data],\r\n  #\"Removed Other Columns\" = Table.SelectColumns(dbo_Products, {\"ProductId\", \"Title\", \"Description\", \"ProductCategory\", \"UnitCost\", \"ListPrice\", \"ProductImageUrl\"}),\r\n  #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\", {{\"Title\", \"Product\"}}),\r\n  #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"ProductCategory\", Splitter.SplitTextByDelimiter(\" > \", QuoteStyle.Csv), {\"ProductCategory.1\", \"ProductCategory.2\"}),\r\n  #\"Changed Type\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\", {{\"ProductCategory.1\", type text}, {\"ProductCategory.2\", type text}}),\r\n  #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\", {{\"ProductCategory.1\", \"Category\"}, {\"ProductCategory.2\", \"Subcategory\"}}),\r\n  #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns1\", {{\"UnitCost\", Currency.Type}, {\"ListPrice\", Currency.Type}}),\r\n  #\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type1\", {{\"ProductImageUrl\", \"Product Image\"}})\r\nin\r\n  #\"Renamed Columns2\";\r\nshared Orders = let\r\n  Source = Sql.Database(\"cpt.database.windows.net\", \"WingtipSalesDB\"),\r\n  dbo_Invoices = Source{[Schema = \"dbo\", Item = \"Invoices\"]}[Data],\r\n  #\"Removed Other Columns\" = Table.SelectColumns(dbo_Invoices, {\"InvoiceId\", \"InvoiceType\"}),\r\n  #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Other Columns\", \"InPerson\", \"Store Purchases\", Replacer.ReplaceText, {\"InvoiceType\"}),\r\n  #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\", \"MailOrder\", \"Mail Order Purchases\", Replacer.ReplaceText, {\"InvoiceType\"}),\r\n  #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\", \"Online\", \"Online Purchases\", Replacer.ReplaceText, {\"InvoiceType\"}),\r\n  #\"Renamed Columns\" = Table.RenameColumns(#\"Replaced Value2\", {{\"InvoiceType\", \"Order Type\"}})\r\nin\r\n  #\"Renamed Columns\";\r\nshared Sales = let\r\n  Source = Sql.Database(\"cpt.database.windows.net\", \"WingtipSalesDB\"),\r\n  dbo_InvoiceDetails = Source{[Schema = \"dbo\", Item = \"InvoiceDetails\"]}[Data],\r\n  #\"Changed Type\" = Table.TransformColumnTypes(dbo_InvoiceDetails, {{\"SalesAmount\", Currency.Type}}),\r\n  #\"Expanded Invoices\" = Table.ExpandRecordColumn(#\"Changed Type\", \"Invoices\", {\"InvoiceDate\", \"CustomerId\"}, {\"InvoiceDate\", \"CustomerId\"}),\r\n  #\"Changed Type1\" = Table.TransformColumnTypes(#\"Expanded Invoices\", {{\"InvoiceDate\", type date}}),\r\n  #\"Expanded Products\" = Table.ExpandRecordColumn(#\"Changed Type1\", \"Products\", {\"UnitCost\"}, {\"UnitCost\"}),\r\n  #\"Changed Type2\" = Table.TransformColumnTypes(#\"Expanded Products\", {{\"UnitCost\", Currency.Type}}),\r\n  #\"Added Custom\" = Table.AddColumn(#\"Changed Type2\", \"ProductCost\", each [Quantity] * [UnitCost]),\r\n  #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom\", {{\"ProductCost\", Currency.Type}}),\r\n  #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type3\", {\"UnitCost\"})\r\nin\r\n  #\"Removed Columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Customers","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Customers.csv"},"attributes":[{"name":"CustomerId","dataType":"int64"},{"name":"Customer","dataType":"string"},{"name":"City Name","dataType":"string"},{"name":"State","dataType":"string"},{"name":"Zipcode","dataType":"string"},{"name":"Gender","dataType":"string"},{"name":"BirthDate","dataType":"dateTime"},{"name":"Customer Type","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2019-10-21T17:59:24.4479228+00:00","location":"https://wabieus2cdsap1.blob.core.windows.net:443/913b7aae-5240-416f-b097-58a7ebf1e2da/Customers.csv?snapshot=2019-10-21T17%3A59%3A24.4411716Z"}]},{"$type":"LocalEntity","name":"Products","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Products.csv"},"attributes":[{"name":"ProductId","dataType":"int64"},{"name":"Product","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Category","dataType":"string"},{"name":"Subcategory","dataType":"string"},{"name":"UnitCost","dataType":"decimal"},{"name":"ListPrice","dataType":"decimal"},{"name":"Product Image","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2019-10-21T17:59:55.5031318+00:00","location":"https://wabieus2cdsap1.blob.core.windows.net:443/913b7aae-5240-416f-b097-58a7ebf1e2da/Products.csv?snapshot=2019-10-21T17%3A59%3A55.4048094Z"}]},{"$type":"LocalEntity","name":"Orders","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Orders.csv"},"attributes":[{"name":"InvoiceId","dataType":"int64"},{"name":"Order Type","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2019-10-21T18:00:26.4780502+00:00","location":"https://wabieus2cdsap1.blob.core.windows.net:443/913b7aae-5240-416f-b097-58a7ebf1e2da/Orders.csv?snapshot=2019-10-21T18%3A00%3A26.4715647Z"}]},{"$type":"LocalEntity","name":"Sales","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales.csv"},"attributes":[{"name":"Id","dataType":"int64"},{"name":"Quantity","dataType":"int64"},{"name":"SalesAmount","dataType":"decimal"},{"name":"InvoiceId","dataType":"int64"},{"name":"ProductId","dataType":"int64"},{"name":"InvoiceDate","dataType":"dateTime"},{"name":"CustomerId","dataType":"int64"},{"name":"ProductCost","dataType":"decimal"}],"partitions":[{"name":"Part001","refreshTime":"2019-10-21T18:01:27.5335089+00:00","location":"https://wabieus2cdsap1.blob.core.windows.net:443/913b7aae-5240-416f-b097-58a7ebf1e2da/Sales.csv?snapshot=2019-10-21T18%3A01%3A27.5246769Z"}]}],"relationships":[{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"Customers","attributeName":"CustomerId"},"toAttribute":{"entityName":"Sales","attributeName":"CustomerId"}},{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"Products","attributeName":"ProductId"},"toAttribute":{"entityName":"Sales","attributeName":"ProductId"}},{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"Orders","attributeName":"InvoiceId"},"toAttribute":{"entityName":"Sales","attributeName":"InvoiceId"}}]}